version: '2'

services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app:ro
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DB_HOST: localhost
      DB_USER: root
      DB_PASS: password
      DB_NAME: fusic-robinhard
      DB_PORT: 3306
      DB_CONNECTION: mysql
    links:
      - database
  database:
    image: bitnami/mysql:8.0
    ports:
      - 3306:3306
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=demo_user
      - MYSQL_PASSWORD=demo_pass
      - MYSQL_DATABASE=demo_node_api